:source-highlighter: highlightjs
:numbered:
ifdef::env-github[]
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]


= Introduction

A sample project providing REST endpoints using JAX-RS, CDI, JPA, JTA 
with the https://quarkus.io[Quarkus] framework, showing how to define
properties for different profiles, such as development (dev) 
and production (prod).

The app has two http://h2database.com[H2 database] files inside the link:src/main/resources/META-INF/resources/[resources] dir:

- `h2_db_dev.mv.db` and 
- `h2_db_prod.mv.db`.

They contain just a `User` table with different data to make it clear
that the app is using the dev or prod database.

The link:src/main/resources/application.properties[application.properties]
defines a `%{profile}.quarkus.datasource.url` property for the `dev` and `prod` profiles.

== Building the app

[source, bash]
----
./mvnw clean package
----

== Running the app in the development environment

If you want to run the app in the development environement,
in order to use hot deployment, you can execute

[source, bash]
----
./mvnw compile quarkus:dev
----

That will enable the `dev` profile, so that the development database will be used.
You can access the application at http://localhost:8080/, which provides links to the REST endpoints.
Acessing a link such as http://localhost:8080/api/user/1
will return an user from the development database.

IMPORTANT: Running the app this way, you may have to set the absolute path of the database in the `dev.quarkus.datasource.url` attribute of the link:src/main/resources/application.properties[application.properties] file.

If you just want to use the development or other environement you may have created
inside the application.properties, you can run the app in one of the following ways:

- Using a system variable: `java -Dquarkus-profile=dev -jar target/quarkus-app-runner.jar`
- Using an environment variable: `QUARKUS_PROFILE=dev java -jar target/quarkus-app-runner.jar`

NOTE: Realize the format of the system and environement variables name is different.

== Running the app in the production environment

Running the app with the following command will automatically define the profile as `prod`,
so that the production database will be used.

[source, bash]
----
java -jar quarkus-app-runner.jar
----

If you have other profiles than `dev` and `prod` you can set the profile you want to activate with the commands shown at the previous section.

= References

- https://quarkus.io/guides/application-configuration-guide